### ISSUE TITLE
Add aggregation workflow job

### ISSUE THREAD

**Issue by daniel-sol** [equinor/fmu-sumo-sim2sumo#23]
The aggregation of table results are per today only available in the front end of sumo. This should be added somewhere. 
Is this the logical place to add it?

**Comment by equinor-ruaj** [comment]
No longer relevant.
"Table aggregation" is no longer done in bulk. Instead, large tables are split into fragments of up to 500 columns: https://github.com/equinor/sumo-fmu-aggregation-service/pull/318

We might create a task similar to this later where the table splitting is done in sim2sumo instead of the aggregation service.
